language: node_js
node_js:
- 8.10.0

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
  - node_modules

install:
- yarn install

script:
- yarn test

after_failure:
- sudo cat /var/log/syslog

deploy:
  provider: npm
  email: "rps.devops@deliveryhero.com"
  api_key: $NPM_KEY
  on:
    tags: true
